services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "YourStrong@Passw0rd"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "if [ -f /var/opt/mssql/data/master.mdf ]; then exit 0; else exit 1; fi"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 40s

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: pfm
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  pfm-api:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./Pfm.Api:/app/swagger
      - ./Pfm.Api/appsettings.Docker.json:/app/appsettings.json
    environment:
      - ASPNETCORE_ENVIRONMENT=Development 
      - ASPNETCORE_URLS=http://*:8080
    depends_on:
      sqlserver:
        condition: service_healthy
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  sqlserver_data:
  postgres_data: 